# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import client_server_pb2 as client__server__pb2


class DataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendWebhookData = channel.unary_unary(
                '/Data/SendWebhookData',
                request_serializer=client__server__pb2.DataRequest.SerializeToString,
                response_deserializer=client__server__pb2.DataResponse.FromString,
                )


class DataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendWebhookData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendWebhookData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWebhookData,
                    request_deserializer=client__server__pb2.DataRequest.FromString,
                    response_serializer=client__server__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendWebhookData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Data/SendWebhookData',
            client__server__pb2.DataRequest.SerializeToString,
            client__server__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
