version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_python
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py makemigrations &&
              python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
  
  
  grpc-server:
    container_name: grpc-server
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "npm install grpc &&
            npm install && node server.js"

